package com.luckybox.admin.campaign;

public record AdminCampaignResponse(
		long id,
		String slug,
		String title,
		String subtitle,
		String description,
		String coverImageUrl,
		String bannerImageUrl,
		String sourceType,
		String sourceTypeLabel,
		boolean commercialUseConfirmed,
		boolean officialLicenseConfirmed,
		String rightsNotice,
		boolean ageRestricted,
		Integer minimumAge,
		String ageVerificationNote,
		String ipName,
		String brandName,
		int pricePerDraw,
		int totalTickets,
		int remainingTickets,
		int soldTickets,
		int prizeCount,
		String status,
		String statusLabel,
		String salesStartAt,
		String salesEndAt,
		String shippingNote,
		String returnPolicyNote,
		boolean hasLastPrize,
		String lastPrizeRule,
		String fairnessMode,
		String seedHash,
		String createdAt,
		String updatedAt) {
}
